package com.example.trabajoandroid


import android.content.Context
import com.example.trabajoandroid.R.string

class ListaComida {
    public fun crearListaComida(context: Context): MutableList<Comida> {
        val listaTotalComida: MutableList<Comida> = mutableListOf()
        listaTotalComida.add(
            Comida(
                context.getString(string.Scones),
                false,
                R.drawable.scones,
                12.2,
                context.getString(string.Descrip_scones),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.SuperScones),
                false,
                R.drawable.superscones,
                4.5,
                context.getString(string.Descrip_superScones),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.CarneCruda),
                true,
                R.drawable.carne,
                43.4,
                context.getString(string.Descrip_carneCruda),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.Bistek),
                true,
                R.drawable.carne,
                12.2,
                context.getString(string.Descrip_Bistek),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.CocaCola),
                false,
                R.drawable.cocacola,
                4.6,
                context.getString(string.Descrip_coccaCola),
                true,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.SupDes),
                false,
                R.drawable.supdesa,
                12.4,
                context.getString(string.Descrip_supDesay),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.DesaCom),
                false,
                R.drawable.desayuno,
                6.2,
                context.getString(string.Descrip_desaCompl),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.OjoDedios),
                true,
                R.drawable.ojosdedios,
                20.2,
                context.getString(string.Descrip_ojoDeDios),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.BolasCarne),
                true,
                R.drawable.bolabuenas,
                12.2,
                context.getString(string.Descrip_boCar),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.AlgodonDeAzucar),
                false,
                R.drawable.algoazu,
                23.2,
                context.getString(string.Descrip_algoAzu),
                false,
                true
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.BeiQue),
                true,
                R.drawable.beiconcrudo,
                9.5,
                context.getString(string.Descrip_beQue),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.Buñuelos),
                false,
                R.drawable.bunuelos,
                23.2,
                context.getString(string.Descrip_buñuelos),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.PolloPohe),
                true,
                R.drawable.pollohecho,
                15.2,
                context.getString(string.Descrip_polPoHec),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.PolloFrito),
                true,
                R.drawable.pollofrito,
                7.6,
                context.getString(string.Descrip_polFri),
                false,
                false
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.TartaQueso),
                false,
                R.drawable.tartadequeso,
                12.6,
                "tarta de queso",
                false,
                true
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.Helado),
                false,
                R.drawable.helado,
                9.34,
                "helado",
                false,
                true
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.HeladoTri),
                false,
                R.drawable.heladotri,
                11.2,
                "helado con 3 bolas",
                false,
                true
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.HeladoCu),
                false,
                R.drawable.heladocu,
                15.99,
                "helado con 4 bolas",
                false,
                true
            )
        )
        return listaTotalComida
    }
}