package com.example.trabajoandroid.ViewModel


import android.content.Context
import com.example.trabajoandroid.Model.Comida
import com.example.trabajoandroid.R
import com.example.trabajoandroid.R.string

class ListaComida {
    fun crearListaComida(context: Context): MutableList<Comida> {
        val listaTotalComida: MutableList<Comida> = mutableListOf()
        listaTotalComida.add(
            Comida(
                context.getString(string.Scones),
                false,
                R.drawable.scones,
                12.2,
                context.getString(string.Descrip_scones),
                false,
                false,
                context.getString(string.video_Scones),
                3.1f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.SuperScones),
                false,
                R.drawable.superscones,
                4.5,
                context.getString(string.Descrip_superScones),
                false,
                false,
                context.getString(string.video_SuperScones),
                5.0f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.CarneCruda),
                true,
                R.drawable.carne,
                43.4,
                context.getString(string.Descrip_carneCruda),
                false,
                false,
                context.getString(string.video_carne),
                2.9f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.Bistek),
                true,
                R.drawable.bistek,
                12.2,
                context.getString(string.Descrip_Bistek),
                false,
                false,
                context.getString(string.video_bistek),
                4.3f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.CocaCola),
                false,
                R.drawable.cocacola,
                4.6,
                context.getString(string.Descrip_coccaCola),
                true,
                false,
                context.getString(string.video_cocaCola),
                3.7f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.SupDes),
                false,
                R.drawable.supdesa,
                12.4,
                context.getString(string.Descrip_supDesay),
                false,
                false,
                context.getString(string.video_superdesa),
                4.3f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.DesaCom),
                false,
                R.drawable.desayuno,
                6.2,
                context.getString(string.Descrip_desaCompl),
                false,
                false,
                context.getString(string.video_desayuno),
                2.7f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.OjoDedios),
                true,
                R.drawable.ojosdedios,
                20.2,
                context.getString(string.Descrip_ojoDeDios),
                false,
                false,
                context.getString(string.video_ojosdedios),
                5.0f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.BolasCarne),
                true,
                R.drawable.bolabuenas,
                12.2,
                context.getString(string.Descrip_boCar),
                false,
                false,
                context.getString(string.video_bolasbuenas),
                2.2f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.AlgodonDeAzucar),
                false,
                R.drawable.algoazu,
                23.2,
                context.getString(string.Descrip_algoAzu),
                false,
                true,
                context.getString(string.video_algoazu),
                3.7f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.BeiQue),
                true,
                R.drawable.beiconcrudo,
                9.5,
                context.getString(string.Descrip_beQue),
                false,
                false,
                context.getString(string.video_beiconcrudo),
                4.5f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.Buñuelos),
                false,
                R.drawable.bunuelos,
                23.2,
                context.getString(string.Descrip_buñuelos),
                false,
                false,
                context.getString(string.video_bunuelos),
                4.2f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.PolloPohe),
                true,
                R.drawable.pollohecho,
                15.2,
                context.getString(string.Descrip_polPoHec),
                false,
                false,
                context.getString(string.video_pollohecho),
                1.5f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.PolloFrito),
                true,
                R.drawable.pollofrito,
                7.6,
                context.getString(string.Descrip_polFri),
                false,
                false,
                context.getString(string.video_pollofrito),
                5.0f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.TartaQueso),
                false,
                R.drawable.tartadequeso,
                12.6,
                context.getString(string.Descrip_tarQue),
                false,
                true,
                context.getString(string.video_tartadequeso),
                5.0f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.Helado),
                false,
                R.drawable.helado,
                9.34,
                context.getString(string.Descrip_helado),
                false,
                true,
                context.getString(string.video_helado),
                4.8f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.HeladoTri),
                false,
                R.drawable.heladotri,
                11.2,
                context.getString(string.Descrip_helado3),
                false,
                true,
                context.getString(string.video_heladotri),
                3.6f
            )
        )
        listaTotalComida.add(
            Comida(
                context.getString(string.HeladoCu),
                false,
                R.drawable.heladocu,
                15.99,
                context.getString(string.Descrip_helado4),
                false,
                true,
                context.getString(string.video_heladocu),
                2.2f
            )
        )
        return listaTotalComida
    }
}